spring.application.name=JustEat

server.port = 8090
spring.datasource.url=jdbc:postgresql://localhost:5432/justeat
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=admin
cloudinary.cloud-name=droy74tj6
cloudinary.api-key=746653789958985
cloudinary.api-secret=CcjewmLE5pnm8bWRAzsBvl1o6kU

# File upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB