spring.application.name=JustEat

server.port=${PORT:8090}

# Database Configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-dark-sound-aooyrn8n-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_9I7eConkjVAs}
spring.datasource.url=jdbc:postgresql://localhost:5432/justeat
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:droy74tj6}
cloudinary.api-key=${CLOUDINARY_API_KEY:746653789958985}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:CcjewmLE5pnm8bWRAzsBvl1o6kU}

# File upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mail Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=${SPRING_MAIL_USERNAME:justeat306@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:sjgz dozp kyji yoql}
